# Wingman Test Suite Configuration
wingman_binary_path: /Users/sarangsharma/code/bito-wingman/build/bitowingman
wingman_config_path: /Users/sarangsharma/.bitowingman/config.json
perplexity_key: YOUR_PERPLEXITY_API_KEY_HERE
run_count: 1
parallel_workers: 3

repos:
  - repo_path: /Users/sarangsharma/code/faultline
    branch: chunking-test-issue-2
    inputs_path: /Users/sarangsharma/code/inputs
    output_path: /Users/sarangsharma/code/outputs
