# Wingman Test Suite Configuration
wingman_binary_path: /path/to/your/bitowingman/binary
wingman_config_path: /path/to/your/.bitowingman/config.json
perplexity_key: your_perplexity_api_key_here
run_count: 2
parallel_workers: 2

repos:
  - repo_path: /path/to/your/repo
    branch: your-branch-name
    inputs_path: /path/to/your/inputs
    output_path: /path/to/your/outputs
